server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/html/public;

    # Логи
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Статические файлы
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
        expires max;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }


    # Обработка PHP файлов
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param APP_ENV development;

        # Таймауты Default - 60s
        fastcgi_read_timeout 20;
        fastcgi_connect_timeout 20;
        fastcgi_send_timeout 20;
    }

    # Запрет доступа к скрытым файлам
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Запрет доступа к некоторым директориям
    location ~ ^/(\.git|\.env|storage|bootstrap|vendor|database|tests) {
        deny all;
        return 404;
    }
}